version: '3'

services:
  web:
    build: .
    command: python src/tupan/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:fatec@db:5432:/tupan
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB: tupan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fatec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
volumes:
  postgres_data:

