# Generated by Django 5.1.1 on 2024-10-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Nome do alerta', max_length=127, unique=True)),
                ('condicao', models.CharField(help_text='Condição para o alerta acontecer', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
                ('estacao_parametro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaoparametro')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('timestamp', models.BigIntegerField(help_text='Data/hora do alerta em timestamp')),
                ('timestamp_convertido', models.DateTimeField(blank=True, help_text='Data/hora do alerta em datetime', null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alertas', to='alertas.alerta')),
            ],
            options={
                'verbose_name': 'Histórico de Alerta',
                'verbose_name_plural': 'Históricos de Alertas',
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('timestamp', models.BigIntegerField(help_text='Data/hora da medição em timestamp')),
                ('timestamp_convertido', models.DateTimeField(blank=True, help_text='Data/hora da medição em datetime', null=True)),
                ('dados', models.CharField(help_text='Valor dos dados da medição', max_length=63)),
                ('estacao_parametro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaoparametro')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
            },
        ),
    ]
