# Generated by Django 5.1.1 on 2024-10-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('estacoes', '0002_alter_estacaoparametro_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='estacao_parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaoparametro'),
        ),
    ]
