# Generated by Django 5.1.1 on 2024-11-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alter_alerta_estacao_parametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoalerta',
            name='medicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historico_alertas', to='alertas.medicao'),
        ),
    ]
