# Generated by Django 5.1.1 on 2024-09-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alter_alerta_condicao_alter_alerta_nome_and_more'),
        ('estacoes', '0004_estacao_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estacao_parametro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaoparametro'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='estacao_parametro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaoparametro'),
        ),
    ]
