# Generated by Django 5.1.1 on 2024-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='parametros',
        ),
        migrations.AddField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
