# Generated by Django 5.1.1 on 2024-11-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0002_alter_estacaoparametro_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='nome',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
