# Generated by Django 5.1.1 on 2024-09-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0002_remove_estacao_parametros_endereco_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacao')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.parametro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
