# Generated by Django 5.1.1 on 2024-09-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0003_estacaoparametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='parametros',
            field=models.ManyToManyField(blank=True, through='estacoes.EstacaoParametro', to='estacoes.parametro'),
        ),
    ]
