# Generated by Django 5.1.1 on 2024-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0004_estacao_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='unidade',
        ),
        migrations.AddField(
            model_name='parametro',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do que abrange o parâmetro', max_length=255),
        ),
    ]
