# Generated by Django 5.1.1 on 2024-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0005_remove_parametro_unidade_parametro_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.CharField(help_text='Unidade de medida do parâmetro', max_length=30)),
                ('nome', models.CharField(help_text='Nome da categoria do parâmetro', max_length=127)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
