name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set permissions for private key
      run: |
        echo "${{ secrets.KEYAWS }}" > key.pem
        chmod 600 key.pem

    - name: Stop running containers
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@98.80.44.121 'if [ -d /home/ubuntu/tupan-back/ ]; then cd /home/ubuntu/tupan-back/ && sudo docker-compose down; fi'

    - name: Deploy to EC2
      run: |
        rsync -av --delete ./ ubuntu@98.80.44.121:/home/ubuntu/tupan-back

    - name: Run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@98.80.44.121 'cd /home/ubuntu/tupan-back && sudo docker-compose up -d'

    - name: Cleanup
      run: |
        rm -f key.pem
