name: Django CI & Deploy

on:
  push:
    branches:
      - '*'  # Trigger for push in any branch
  pull_request:
    branches:
      - main  # Trigger for pull request to main branch

jobs:
  # Job for running tests
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USERNAME }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USERNAME }}; do
          echo "Waiting for PostgreSQL...";
          sleep 5;
        done

    - name: Apply Django Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests
      run: |
        pytest

  # Job for deploying to AWS EC2, only if the build job is successful
  deploy:
    runs-on: ubuntu-24.04
    needs: build  # This job will only run if the build job is successful
    if: github.ref == 'refs/heads/main'  # Run only on push to the main branch
    env:
      AWS_PRIVATE_KEY: ${{ secrets.KEYAWS }}
      SSH_OPTIONS: '-o StrictHostKeyChecking=no -i key.pem ubuntu@98.80.44.121'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Stop running containers
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'if [ -d /home/ubuntu/tupan-back/ ]; then cd /home/ubuntu/tupan-back/ && sudo docker-compose down; fi'

      - name: Create target directory on AWS instance
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'mkdir -p /home/ubuntu/tupan-back/'

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DB_USER=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Transfer code to AWS instance
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' --exclude='.husky' -e "ssh -o StrictHostKeyChecking=no -i key.pem" --rsync-path="sudo rsync" ./ ubuntu@98.80.44.121:/home/ubuntu/tupan-back

      - name: Set permissions for entrypoint
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'cd /home/ubuntu/tupan-back/ && sudo chmod +x entrypoint.sh'

      - name: Build Docker Compose
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'cd /home/ubuntu/tupan-back/ && sudo docker-compose build'

      - name: Run Docker Compose
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'cd /home/ubuntu/tupan-back/ && sudo docker-compose up -d'

      - name: Cleanup SSH key
        run: |
          rm -f key.pem
